Completion of tnc_tool.

diff --git a/tnc_tool b/tnc_tool
--- a/tnc_tool
+++ b/tnc_tool
@@ -1,7 +1,7 @@
 #!/bin/bash
 # PVM Two Node Cluster Management tool
 scriptname="tnc_tool"
-scriptversion="0.0.1"
+scriptversion="0.1.0"
 
 cat="/bin/cat"
 cut="/bin/cut"
@@ -34,8 +34,8 @@ tnc_status()
 	$service gfs2 status | $sed -e "s/GFS2 mountpoints/FileSystems/"
 }
 	
-# this function stop sync operation on this node ...
-tnc_stopsync()
+# this function stop sync/cluster operations on this node ...
+tnc_stop()
 {
 	local vml 	# List of running virtual machines on this node
 	echo "You want to stop data syncronization on this node ($($uname -n)),"
@@ -45,8 +45,10 @@ tnc_stopsync()
 	
 	vml=$( $pvmctl "status" | $sed -e "1d" )
 	for i in $vml; do
+		echo "Stopping $i ..."
 		$pcad stop $i
 	done
+	/pvm/Scripts/pvmctl unloadvsws
 	echo "Stopping filesystem ..."
 	$service gfs2 stop >/dev/null 2>&1
 	if [[ $? -ne 0 ]]; then
@@ -65,6 +67,45 @@ tnc_stopsync()
 		echo_error "Can't stop sync operation ..."
 		exit 1
 	fi
+
+	echo "Stopping cluster operation ..."
+	$service rgmanager stop >/dev/null 2>&1
+	$service ricci stop >/dev/null 2>&1
+	$service cman stop >/dev/null 2>&1
+}
+
+tnc_startsync()
+{
+	echo "Starting sync operation ..."
+	$service drbd start >/dev/null 2>&1
+	if [[ $? -ne 0 ]]; then
+		echo "Error: Can't start sync operation ..."
+		exit 1
+	fi
+	echo "Make Primary ..."
+	$drbdadm primary pvm >/dev/null 2>&1
+	if [[ $? -ne 0 ]]; then
+		echo "Error: Can't change state to primary ..."
+		exit 1
+	fi
+}
+
+tnc_startpvm()
+{
+	echo "Starting cluster ..."
+	$service cman start >/dev/null 2>&1
+	if [[ $? -ne "0" ]]; then
+		echo "Error: Can't start cluster engine ..."
+		exit 1
+	fi
+	$service ricci start >/dev/null 2>&1
+	$service gfs2 start >/dev/null 2>&1 
+	$service rgmanager start >/dev/null 2>&1
+	if [[ $? -ne "0" ]]; then
+		echo "Error: Can't start resourse manager ..."
+		exit 1
+	fi
+	/pvm/Scripts/pvmctl loadvsws 
 }
 
 tnc_help()
@@ -74,7 +115,9 @@ $scriptname $scriptversion
 $scriptname is PVM two node cluster managent tool.
 
         usage:  status			- printout data-sync status of cluster
-                stopsync		- stop data-sync operation, preparing node to shutdown
+                stop			- stop pvm operation, preparing node to shutdown
+                startsync		- start pvm sync-operation
+                startpvm		- start pvm operation
 	end-of-help
 }
 
@@ -82,8 +125,14 @@ case "$1" in
 	"status")
 		tnc_status
 		;;
-	"stopsync")
-		tnc_stopsync
+	"stop")
+		tnc_stop
+		;;
+	"startsync")
+		tnc_startsync
+		;;
+	"startpvm")
+		tnc_startpvm
 		;;
 	"help")
 		tnc_help
